services: 
  web: 
    build: YourWayAPI 
    env_file:
      - .env
    environment:
      - ACCESS_TOKEN_VK_AUTH:${ACCESS_TOKEN_VK_AUTH}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    ports: 
      - '8000:8000'
    networks:
      back_db_front: {}

networks:
  back_db_front:
    external: true