services:
  nginx:
    depends_on:
      - web
    image: nginx:latest
    ports:
      - '85:85'
    volumes:
      # Заменить на свой nginx конфиг
      - ./nginx:/etc/nginx/conf.d
      # Монтируем папку с логами на хост машину для более удобного доступа
      - ./logs:/var/log/nginx/
    networks:
      back_db_front: {}
    restart: always

  web: 
    build: ./YourWayAPI/
    env_file:
      - .env
    environment:
      - ACCESS_TOKEN_VK_AUTH:${ACCESS_TOKEN_VK_AUTH}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    ports: 
      - '8000:8000'
    networks:
      back_db_front: {}

networks:
  back_db_front:
    external: true